IPCC_AR4_20C3M_EXP_START_DATES_DICT = {'ncar_pcm1': {'IPCCModelID': 'PCM',
                                                     'RunList': ['Run 1', 'Run 2', 'Run 3', 'Run 4'],
                                                     'Run 2': {'MonthsSimulated': 1320,
                                                               'FirstAvailableYear': 1890,
                                                               'YearInBaseRun': '120 @ 1870',
                                                               'FirstAvailableMonth': 1,
                                                               'YearsSimulated': 110,
                                                               'LastAvailableMonth': 12,
                                                               'BaseRun': 'PIcntrl ',
                                                               'LastAvailableYear': 1999,
                                                               'BaseRealization': 'Run1'},
                                                     'Run 3': {'MonthsSimulated': 1320,
                                                               'FirstAvailableYear': 1890,
                                                               'YearInBaseRun': '110 @ 1870',
                                                               'FirstAvailableMonth': 1,
                                                               'YearsSimulated': 110,
                                                               'LastAvailableMonth': 12,
                                                               'BaseRun': 'PIcntrl ',
                                                               'LastAvailableYear': 1999,
                                                               'BaseRealization': 'Run1'},
                                                     'Run 1': {'MonthsSimulated': 1320,
                                                               'FirstAvailableYear': 1890,
                                                               'YearInBaseRun': '130 @ 1870',
                                                               'FirstAvailableMonth': 1,
                                                               'YearsSimulated': 110,
                                                               'LastAvailableMonth': 12,
                                                               'BaseRun': 'PIcntrl ',
                                                               'LastAvailableYear': 1999,
                                                               'BaseRealization': 'Run1'},
                                                     'Run 4': {'MonthsSimulated': 1320,
                                                               'FirstAvailableYear': 1890,
                                                               'YearInBaseRun': '100 @ 1870',
                                                               'FirstAvailableMonth': 1,
                                                               'YearsSimulated': 110,
                                                               'LastAvailableMonth': 12,
                                                               'BaseRun': 'PIcntrl ',
                                                               'LastAvailableYear': 1999,
                                                               'BaseRealization': 'Run1'}
                                                     },
                                       'iap_fgoals1_0_g': {'IPCCModelID': 'FGOALS-g1.0',
                                                           'RunList': ['Run 1', 'Run 2', 'Run 3'],
                                                           'Run 2': {'MonthsSimulated': 1800,
                                                                     'FirstAvailableYear': 1850,
                                                                     'YearInBaseRun': 1855,
                                                                     'FirstAvailableMonth': 1,
                                                                     'YearsSimulated': 150,
                                                                     'LastAvailableMonth': 12,
                                                                     'BaseRun': 'PIcntrl  ',
                                                                     'LastAvailableYear': 1999,
                                                                     'BaseRealization': 'Run1'},
                                                           'Run 1': {'MonthsSimulated': 1800,
                                                                     'FirstAvailableYear': 1850,
                                                                     'YearInBaseRun': 1850,
                                                                     'FirstAvailableMonth': 1,
                                                                     'YearsSimulated': 150,
                                                                     'LastAvailableMonth': 12,
                                                                     'BaseRun': 'PIcntrl  ',
                                                                     'LastAvailableYear': 1999,
                                                                     'BaseRealization': 'Run1'},
                                                           'Run 3': {'MonthsSimulated': 1800,
                                                                     'FirstAvailableYear': 1850,
                                                                     'YearInBaseRun': 1860,
                                                                     'FirstAvailableMonth': 1,
                                                                     'YearsSimulated': 150,
                                                                     'LastAvailableMonth': 12,
                                                                     'BaseRun': 'PIcntrl  ',
                                                                     'LastAvailableYear': 1999,
                                                                     'BaseRealization': 'Run1'}
                                                           },
                                       'cnrm_cm3': {'IPCCModelID': 'CNRM-CM3',
                                                    'RunList': ['Run 1'],
                                                    'Run 1': {'MonthsSimulated': 1680,
                                                              'FirstAvailableYear': 1860,
                                                              'YearInBaseRun': 2040,
                                                              'FirstAvailableMonth': 1,
                                                              'YearsSimulated': 140,
                                                              'LastAvailableMonth': 12,
                                                              'BaseRun': 'PIcntrl  ',
                                                              'LastAvailableYear': 1999,
                                                              'BaseRealization': 'Run1'},
                                                    },
                                       'csiro_mk3_0': {'IPCCModelID': 'CSIRO-Mk3.0',
                                                       'RunList': ['Run 1', 'Run 2', 'Run 3'],
                                                       'Run 1': {'MonthsSimulated': 1560,
                                                                 'FirstAvailableYear': 1871,
                                                                 'YearInBaseRun': 1871,
                                                                 'FirstAvailableMonth': 1,
                                                                 'YearsSimulated': 130,
                                                                 'LastAvailableMonth': 12,
                                                                 'BaseRun': 'PIcntrl  ',
                                                                 'LastAvailableYear': 2000,
                                                                 'BaseRealization': 'Run1'},
                                                       'Run 2': {'MonthsSimulated': 1560,
                                                                 'FirstAvailableYear': 1871,
                                                                 'YearInBaseRun': 1881,
                                                                 'FirstAvailableMonth': 1,
                                                                 'YearsSimulated': 130,
                                                                 'LastAvailableMonth': 12,
                                                                 'BaseRun': 'PIcntrl  ',
                                                                 'LastAvailableYear': 2000,
                                                                 'BaseRealization': 'Run1'},
                                                       'Run 3': {'MonthsSimulated': 1560,
                                                                 'FirstAvailableYear': 1871,
                                                                 'YearInBaseRun': 1891,
                                                                 'FirstAvailableMonth': 1,
                                                                 'YearsSimulated': 130,
                                                                 'LastAvailableMonth': 12,
                                                                 'BaseRun': 'PIcntrl  ',
                                                                 'LastAvailableYear': 2000,
                                                                 'BaseRealization': 'Run1'},
                                                       },
                                       'inmcm3_0': {'IPCCModelID': 'INM-CM3.0',
                                                    'RunList': ['Run 1'],
                                                    'Run 1': {'MonthsSimulated': 1560,
                                                              'FirstAvailableYear': 1871,
                                                              'YearInBaseRun': 1871,
                                                              'FirstAvailableMonth': 1,
                                                              'YearsSimulated': 130,
                                                              'LastAvailableMonth': 12,
                                                              'BaseRun': 'PIcntrl',
                                                              'LastAvailableYear': 2000,
                                                              'BaseRealization': 'Run1'},
                                                    },
                                       'miroc3_2_medres': {'IPCCModelID': 'MIROC3.2(medres)',
                                                           'RunList': ['Run 1', 'Run 2', 'Run 3'],
                                                           'Run 2': {'MonthsSimulated': 1812,
                                                                     'FirstAvailableYear': 1850,
                                                                     'YearInBaseRun': 2400,
                                                                     'FirstAvailableMonth': 1,
                                                                     'YearsSimulated': 151,
                                                                     'LastAvailableMonth': 12,
                                                                     'BaseRun': 'PIcntrl  ',
                                                                     'LastAvailableYear': 2000,
                                                                     'BaseRealization': 'Run1'},
                                                           'Run 1': {'MonthsSimulated': 1812,
                                                                     'FirstAvailableYear': 1850,
                                                                     'YearInBaseRun': 2300,
                                                                     'FirstAvailableMonth': 1,
                                                                     'YearsSimulated': 151,
                                                                     'LastAvailableMonth': 12,
                                                                     'BaseRun': 'PIcntrl  ',
                                                                     'LastAvailableYear': 2000,
                                                                     'BaseRealization': 'Run1'},
                                                           'Run 3': {'MonthsSimulated': 1812,
                                                                     'FirstAvailableYear': 1850,
                                                                     'YearInBaseRun': 2500,
                                                                     'FirstAvailableMonth': 1,
                                                                     'YearsSimulated': 151,
                                                                     'LastAvailableMonth': 12,
                                                                     'BaseRun': 'PIcntrl  ',
                                                                     'LastAvailableYear': 2000,
                                                                     'BaseRealization': 'Run1'},
                                                           },
                                       'ipsl_cm4': {'IPCCModelID': 'IPSL-CM4',
                                                    'RunList': ['Run 1'],
                                                    'Run 1': {'MonthsSimulated': 1692,
                                                              'FirstAvailableYear': 1860,
                                                              'YearInBaseRun': 1860, 'FirstAvailableMonth': 1,
                                                              'YearsSimulated': 141, 'LastAvailableMonth': 12,
                                                              'BaseRun': 'PIcntrl  ', 'LastAvailableYear': 2000,
                                                              'BaseRealization': 'Run1'},
                                                    },
                                       'giss_aom': {'IPCCModelID': 'GISS-AOM',
                                                    'RunList': ['Run 1', 'Run 2'],
                                                    'Run 2': {'MonthsSimulated': 1812,
                                                              'FirstAvailableYear': 1850,
                                                              'YearInBaseRun': 1850,
                                                              'FirstAvailableMonth': 1,
                                                              'YearsSimulated': 151,
                                                              'LastAvailableMonth': 12,
                                                              'BaseRun': 'PIcntrl  ',
                                                              'LastAvailableYear': 2000,
                                                              'BaseRealization': 'Run2'},
                                                    'Run 1': {'MonthsSimulated': 1812,
                                                              'FirstAvailableYear': 1850,
                                                              'YearInBaseRun': 1850,
                                                              'FirstAvailableMonth': 1,
                                                              'YearsSimulated': 151,
                                                              'LastAvailableMonth': 12,
                                                              'BaseRun': 'PIcntrl  ',
                                                              'LastAvailableYear': 2000,
                                                              'BaseRealization': 'Run1'},
                                                    },
                                       'giss_model_e_h': {'IPCCModelID': 'GISS-EH',
                                                          'RunList': ['Run 1','Run 2', 'Run 3', 'Run 4', 'Run 5'],
                                                          'Run 2': {'MonthsSimulated': 1440,
                                                                    'FirstAvailableYear': 1880,
                                                                    'YearInBaseRun': 2010,
                                                                    'FirstAvailableMonth': 1,
                                                                    'YearsSimulated': 120,
                                                                    'LastAvailableMonth': 12,
                                                                    'BaseRun': 'PIcntrl',
                                                                    'LastAvailableYear': 1999,
                                                                    'BaseRealization': 'Run1'},
                                                          'Run 3': {'MonthsSimulated': 1440,
                                                                    'FirstAvailableYear': 1880,
                                                                    'YearInBaseRun': 2020,
                                                                    'FirstAvailableMonth': 1,
                                                                    'YearsSimulated': 120,
                                                                    'LastAvailableMonth': 12,
                                                                    'BaseRun': 'PIcntrl',
                                                                    'LastAvailableYear': 1999,
                                                                    'BaseRealization': 'Run1'},
                                                          'Run 1': {'MonthsSimulated': 1440,
                                                                    'FirstAvailableYear': 1880,
                                                                    'YearInBaseRun': 2000,
                                                                    'FirstAvailableMonth': 1,
                                                                    'YearsSimulated': 120,
                                                                    'LastAvailableMonth': 12,
                                                                    'BaseRun': 'PIcntrl',
                                                                    'LastAvailableYear': 1999,
                                                                    'BaseRealization': 'Run1'},
                                                          'Run 4': {'MonthsSimulated': 1440,
                                                                    'FirstAvailableYear': 1880,
                                                                    'YearInBaseRun': 2030,
                                                                    'FirstAvailableMonth': 1,
                                                                    'YearsSimulated': 120,
                                                                    'LastAvailableMonth': 12,
                                                                    'BaseRun': 'PIcntrl',
                                                                    'LastAvailableYear': 1999,
                                                                    'BaseRealization': 'Run1'},
                                                          'Run 5': {'MonthsSimulated': 1476,
                                                                    'FirstAvailableYear': 1880,
                                                                    'YearInBaseRun': 2040,
                                                                    'FirstAvailableMonth': 1,
                                                                    'YearsSimulated': 123,
                                                                    'LastAvailableMonth': 12,
                                                                    'BaseRun': 'PIcntrl',
                                                                    'LastAvailableYear': 2002,
                                                                    'BaseRealization': 'Run1'},
                                                          },
                                       'miroc3_2_hires': {'IPCCModelID': 'MIROC3.2(hires)',
                                                          'RunList': ['Run 1'],
                                                          'Run 1': {'MonthsSimulated': 1212,
                                                                    'FirstAvailableYear': 1900,
                                                                    'YearInBaseRun': 1,
                                                                    'FirstAvailableMonth': 1,
                                                                    'YearsSimulated': 101,
                                                                    'LastAvailableMonth': 12,
                                                                    'BaseRun': 'PIcntrl  ',
                                                                    'LastAvailableYear': 2000,
                                                                    'BaseRealization': 'Run1'},
                                                          },
                                       'ukmo_hadgem1': {'IPCCModelID': 'UKMO-HadGEM1',
                                                        'RunList': ['Run 1','Run 2'],
                                                        'Run 2': {'MonthsSimulated': 1680,
                                                                  'FirstAvailableYear': 1860,
                                                                  'YearInBaseRun': 1960,
                                                                  'FirstAvailableMonth': 1,
                                                                  'YearsSimulated': 140,
                                                                  'LastAvailableMonth': 12,
                                                                  'BaseRun': 'PIcntrl  ',
                                                                  'LastAvailableYear': 1999,
                                                                  'BaseRealization': 'Run1'},
                                                        'Run 1': {'MonthsSimulated': 1680,
                                                                  'FirstAvailableYear': 1860,
                                                                  'YearInBaseRun': 1860,
                                                                  'FirstAvailableMonth': 1,
                                                                  'YearsSimulated': 140,
                                                                  'LastAvailableMonth': 12,
                                                                  'BaseRun': 'PIcntrl  ',
                                                                  'LastAvailableYear': 1999,
                                                                  'BaseRealization': 'Run1'},
                                                        },
                                       'cccma_cgcm3_1': {'IPCCModelID': 'CGCM3.1(T47)',
                                                         'RunList': ['Run 1','Run 2','Run 3','Run 4','Run 5'],
                                                         'Run 2': {'MonthsSimulated': 1812,
                                                                   'FirstAvailableYear': 1850,
                                                                   'YearInBaseRun': 1850,
                                                                   'FirstAvailableMonth': 1,
                                                                   'YearsSimulated': 151,
                                                                   'LastAvailableMonth': 12,
                                                                   'BaseRun': 'PIcntrl  ',
                                                                   'LastAvailableYear': 2000,
                                                                   'BaseRealization': 'Run1'},
                                                         'Run 3': {'MonthsSimulated': 1812,
                                                                   'FirstAvailableYear': 1850,
                                                                   'YearInBaseRun': 1850,
                                                                   'FirstAvailableMonth': 1,
                                                                   'YearsSimulated': 151,
                                                                   'LastAvailableMonth': 12,
                                                                   'BaseRun': 'PIcntrl  ',
                                                                   'LastAvailableYear': 2000,
                                                                   'BaseRealization': 'Run1'},
                                                         'Run 1': {'MonthsSimulated': 1812,
                                                                   'FirstAvailableYear': 1850,
                                                                   'YearInBaseRun': 1850,
                                                                   'FirstAvailableMonth': 1,
                                                                   'YearsSimulated': 151,
                                                                   'LastAvailableMonth': 12,
                                                                   'BaseRun': 'PIcntrl  ',
                                                                   'LastAvailableYear': 2000,
                                                                   'BaseRealization': 'Run1'},
                                                         'Run 4': {'MonthsSimulated': 1812,
                                                                   'FirstAvailableYear': 1850,
                                                                   'YearInBaseRun': 1850,
                                                                   'FirstAvailableMonth': 1,
                                                                   'YearsSimulated': 151,
                                                                   'LastAvailableMonth': 12,
                                                                   'BaseRun': 'PIcntrl  ',
                                                                   'LastAvailableYear': 2000,
                                                                   'BaseRealization': 'Run1'},
                                                         'Run 5': {'MonthsSimulated': 1812,
                                                                   'FirstAvailableYear': 1850,
                                                                   'YearInBaseRun': 1850,
                                                                   'FirstAvailableMonth': 1,
                                                                   'YearsSimulated': 151,
                                                                   'LastAvailableMonth': 12,
                                                                   'BaseRun': 'PIcntrl  ',
                                                                   'LastAvailableYear': 2000,
                                                                   'BaseRealization': 'Run1'}},
                                       'ukmo_hadcm3': {'IPCCModelID': 'UKMO-HadCM3',
                                                       'RunList': ['Run 1','Run 2'],
                                                       'Run 2': {'MonthsSimulated': 1680,
                                                                 'FirstAvailableYear': 1860,
                                                                 'YearInBaseRun': 1860,
                                                                 'FirstAvailableMonth': 1,
                                                                 'YearsSimulated': 140,
                                                                 'LastAvailableMonth': 12,
                                                                 'BaseRun': 'PIcntrl  ',
                                                                 'LastAvailableYear': 1999,
                                                                 'BaseRealization': 'Run1'},
                                                       'Run 1': {'MonthsSimulated': 1680,
                                                                 'FirstAvailableYear': 1860,
                                                                 'YearInBaseRun': 1860,
                                                                 'FirstAvailableMonth': 1,
                                                                 'YearsSimulated': 140,
                                                                 'LastAvailableMonth': 12,
                                                                 'BaseRun': 'PIcntrl  ',
                                                                 'LastAvailableYear': 1999,
                                                                 'BaseRealization': 'Run1'},
                                                       },
                                       'giss_model_e_r': {'IPCCModelID': 'GISS-ER',
                                                          'RunList': ['Run 1','Run 2','Run 3','Run 4','Run 5','Run 6','Run 7','Run 8','Run 9'],
                                                          'Run 8': {'MonthsSimulated': 1488,
                                                                    'FirstAvailableYear': 1880,
                                                                    'YearInBaseRun': 1981,
                                                                    'FirstAvailableMonth': 1,
                                                                    'YearsSimulated': 124,
                                                                    'LastAvailableMonth': 12,
                                                                    'BaseRun': 'PIcntrl',
                                                                    'LastAvailableYear': 2003,
                                                                    'BaseRealization': 'Run1'},
                                                          'Run 9': {'MonthsSimulated': 1488,
                                                                    'FirstAvailableYear': 1880,
                                                                    'YearInBaseRun': 2006,
                                                                    'FirstAvailableMonth': 1,
                                                                    'YearsSimulated': 124,
                                                                    'LastAvailableMonth': 12,
                                                                    'BaseRun': 'PIcntrl',
                                                                    'LastAvailableYear': 2003,
                                                                    'BaseRealization': 'Run1'},
                                                          'Run 2': {'MonthsSimulated': 1488,
                                                                    'FirstAvailableYear': 1880,
                                                                    'YearInBaseRun': 1907,
                                                                    'FirstAvailableMonth': 1,
                                                                    'YearsSimulated': 124,
                                                                    'LastAvailableMonth': 12,
                                                                    'BaseRun': 'PIcntrl',
                                                                    'LastAvailableYear': 2003,
                                                                    'BaseRealization': 'Run1'},
                                                          'Run 3': {'MonthsSimulated': 2652,
                                                                    'FirstAvailableYear': 1880,
                                                                    'YearInBaseRun': 1908,
                                                                    'FirstAvailableMonth': 1,
                                                                    'YearsSimulated': 221,
                                                                    'LastAvailableMonth': 12,
                                                                    'BaseRun': 'PIcntrl',
                                                                    'LastAvailableYear': 2100,
                                                                    'BaseRealization': 'Run1'},
                                                          'Run 1': {'MonthsSimulated': 1488,
                                                                    'FirstAvailableYear': 1880,
                                                                    'YearInBaseRun': 1906,
                                                                    'FirstAvailableMonth': 1,
                                                                    'YearsSimulated': 124,
                                                                    'LastAvailableMonth': 12,
                                                                    'BaseRun': 'PIcntrl',
                                                                    'LastAvailableYear': 2003,
                                                                    'BaseRealization': 'Run1'},
                                                          'Run 7': {'MonthsSimulated': 1488,
                                                                    'FirstAvailableYear': 1880,
                                                                    'YearInBaseRun': 1956,
                                                                    'FirstAvailableMonth': 1,
                                                                    'YearsSimulated': 124,
                                                                    'LastAvailableMonth': 12,
                                                                    'BaseRun': 'PIcntrl',
                                                                    'LastAvailableYear': 2003,
                                                                    'BaseRealization': 'Run1'},
                                                          'Run 4': {'MonthsSimulated': 1488,
                                                                    'FirstAvailableYear': 1880,
                                                                    'YearInBaseRun': 1909,
                                                                    'FirstAvailableMonth': 1,
                                                                    'YearsSimulated': 124,
                                                                    'LastAvailableMonth': 12,
                                                                    'BaseRun': 'PIcntrl',
                                                                    'LastAvailableYear': 2003,
                                                                    'BaseRealization': 'Run1'},
                                                          'Run 5': {'MonthsSimulated': 1488,
                                                                    'FirstAvailableYear': 1880,
                                                                    'YearInBaseRun': 1910,
                                                                    'FirstAvailableMonth': 1,
                                                                    'YearsSimulated': 124,
                                                                    'LastAvailableMonth': 12,
                                                                    'BaseRun': 'PIcntrl',
                                                                    'LastAvailableYear': 2003,
                                                                    'BaseRealization': 'Run1'},
                                                          'Run 6': {'MonthsSimulated': 1488,
                                                                    'FirstAvailableYear': 1880,
                                                                    'YearInBaseRun': 1931,
                                                                    'FirstAvailableMonth': 1,
                                                                    'YearsSimulated': 124,
                                                                    'LastAvailableMonth': 12,
                                                                    'BaseRun': 'PIcntrl',
                                                                    'LastAvailableYear': 2003,
                                                                    'BaseRealization': 'Run1'},
                                                          },
                                       'gfdl_cm2_1': {'IPCCModelID': 'GFDL-CM2.1',
                                                      'RunList': ['Run 1','Run 2','Run 3'],
                                                      'Run 2': {'MonthsSimulated': 1680,
                                                                'FirstAvailableYear': 1861,
                                                                'YearInBaseRun': 41,
                                                                'FirstAvailableMonth': 1,
                                                                'YearsSimulated': 140,
                                                                'LastAvailableMonth': 12,
                                                                'BaseRun': 'PIcntrl  ',
                                                                'LastAvailableYear': 2000,
                                                                'BaseRealization': 'Run1'},
                                                      'Run 1': {'MonthsSimulated': 1680,
                                                                'FirstAvailableYear': 1861,
                                                                'YearInBaseRun': 1,
                                                                'FirstAvailableMonth': 1,
                                                                'YearsSimulated': 140,
                                                                'LastAvailableMonth': 12,
                                                                'BaseRun': 'PIcntrl  ',
                                                                'LastAvailableYear': 2000,
                                                                'BaseRealization': 'Run1'},
                                                      'Run 3': {'MonthsSimulated': 1680,
                                                                'FirstAvailableYear': 1861,
                                                                'YearInBaseRun': 81,
                                                                'FirstAvailableMonth': 1,
                                                                'YearsSimulated': 140,
                                                                'LastAvailableMonth': 12,
                                                                'BaseRun': 'PIcntrl  ',
                                                                'LastAvailableYear': 2000,
                                                                'BaseRealization': 'Run1'},
                                                      },
                                       'gfdl_cm2_0': {'IPCCModelID': 'GFDL-CM2.0',
                                                      'RunList': ['Run 1','Run 2','Run 3'],
                                                      'Run 2': {'MonthsSimulated': 1680,
                                                                'FirstAvailableYear': 1861,
                                                                'YearInBaseRun': 101,
                                                                'FirstAvailableMonth': 1,
                                                                'YearsSimulated': 140,
                                                                'LastAvailableMonth': 12,
                                                                'BaseRun': 'PIcntrl  ',
                                                                'LastAvailableYear': 2000,
                                                                'BaseRealization': 'Run1'},
                                                      'Run 1': {'MonthsSimulated': 1680,
                                                                'FirstAvailableYear': 1861,
                                                                'YearInBaseRun': 1,
                                                                'FirstAvailableMonth': 1,
                                                                'YearsSimulated': 140,
                                                                'LastAvailableMonth': 12,
                                                                'BaseRun': 'PIcntrl  ',
                                                                'LastAvailableYear': 2000,
                                                                'BaseRealization': 'Run1'},
                                                      'Run 3': {'MonthsSimulated': 1680,
                                                                'FirstAvailableYear': 1861,
                                                                'YearInBaseRun': 151,
                                                                'FirstAvailableMonth': 1,
                                                                'YearsSimulated': 140,
                                                                'LastAvailableMonth': 12,
                                                                'BaseRun': 'PIcntrl  ',
                                                                'LastAvailableYear': 2000,
                                                                'BaseRealization': 'Run1'},
                                                      },
                                       'ncar_ccsm3_0': {'IPCCModelID': 'CCSM3',
                                                        'RunList': ['Run 1','Run 2','Run 3','Run 4','Run 5','Run 6','Run 7','Run 8','Run 9'],
                                                        'Run 8': {'MonthsSimulated': 1560,
                                                                  'FirstAvailableYear': 1870,
                                                                  'YearInBaseRun': 460,
                                                                  'FirstAvailableMonth': 1,
                                                                  'YearsSimulated': 130,
                                                                  'LastAvailableMonth': 12,
                                                                  'BaseRun': 'PIcntrl  ',
                                                                  'LastAvailableYear': 1999,
                                                                  'BaseRealization': 'Run2'},
                                                        'Run 9': {'MonthsSimulated': 1560,
                                                                  'FirstAvailableYear': 1870,
                                                                  'YearInBaseRun': 540,
                                                                  'FirstAvailableMonth': 1,
                                                                  'YearsSimulated': 130,
                                                                  'LastAvailableMonth': 12,
                                                                  'BaseRun': 'PIcntrl  ',
                                                                  'LastAvailableYear': 1999,
                                                                  'BaseRealization': 'Run2'},
                                                        'Run 2': {'MonthsSimulated': 1560,
                                                                  'FirstAvailableYear': 1870,
                                                                  'YearInBaseRun': 380,
                                                                  'FirstAvailableMonth': 1,
                                                                  'YearsSimulated': 130,
                                                                  'LastAvailableMonth': 12,
                                                                  'BaseRun': 'PIcntrl  ',
                                                                  'LastAvailableYear': 1999,
                                                                  'BaseRealization': 'Run1'},
                                                        'Run 3': {'MonthsSimulated': 1560,
                                                                  'FirstAvailableYear': 1870,
                                                                  'YearInBaseRun': 400,
                                                                  'FirstAvailableMonth': 1,
                                                                  'YearsSimulated': 130,
                                                                  'LastAvailableMonth': 12,
                                                                  'BaseRun': 'PIcntrl  ',
                                                                  'LastAvailableYear': 1999,
                                                                  'BaseRealization': 'Run1'},
                                                        'Run 1': {'MonthsSimulated': 1560,
                                                                  'FirstAvailableYear': 1870,
                                                                  'YearInBaseRun': 360,
                                                                  'FirstAvailableMonth': 1,
                                                                  'YearsSimulated': 130,
                                                                  'LastAvailableMonth': 12,
                                                                  'BaseRun': 'PIcntrl  ',
                                                                  'LastAvailableYear': 1999,
                                                                  'BaseRealization': 'Run1'},
                                                        'Run 7': {'MonthsSimulated': 1560,
                                                                  'FirstAvailableYear': 1870,
                                                                  'YearInBaseRun': 410,
                                                                  'FirstAvailableMonth': 1,
                                                                  'YearsSimulated': 130,
                                                                  'LastAvailableMonth': 12,
                                                                  'BaseRun': 'PIcntrl  ',
                                                                  'LastAvailableYear': 1999,
                                                                  'BaseRealization': 'Run2'},
                                                        'Run 4': {'MonthsSimulated': 1560,
                                                                  'FirstAvailableYear': 1870,
                                                                  'YearInBaseRun': 420,
                                                                  'FirstAvailableMonth': 1,
                                                                  'YearsSimulated': 130,
                                                                  'LastAvailableMonth': 12,
                                                                  'BaseRun': 'PIcntrl  ',
                                                                  'LastAvailableYear': 1999,
                                                                  'BaseRealization': 'Run1'},
                                                        'Run 5': {'MonthsSimulated': 1560,
                                                                  'FirstAvailableYear': 1870,
                                                                  'YearInBaseRun': 440,
                                                                  'FirstAvailableMonth': 1,
                                                                  'YearsSimulated': 130,
                                                                  'LastAvailableMonth': 12,
                                                                  'BaseRun': 'PIcntrl  ',
                                                                  'LastAvailableYear': 1999,
                                                                  'BaseRealization': 'Run1'},
                                                        'Run 6': {'MonthsSimulated': 1560,
                                                                  'FirstAvailableYear': 1870,
                                                                  'YearInBaseRun': 380,
                                                                  'FirstAvailableMonth': 1,
                                                                  'YearsSimulated': 130,
                                                                  'LastAvailableMonth': 12,
                                                                  'BaseRun': 'PIcntrl  ',
                                                                  'LastAvailableYear': 1999,
                                                                  'BaseRealization': 'Run2'},
                                                        },
                                       'mpi_echam5': {'IPCCModelID': 'ECHAM5/MPI-OM',
                                                      'RunList': ['Run 1','Run 2','Run 3'],
                                                      'Run 2': {'MonthsSimulated': 1692,
                                                                'FirstAvailableYear': 1860,
                                                                'YearInBaseRun': 2215,
                                                                'FirstAvailableMonth': 1,
                                                                'YearsSimulated': 141,
                                                                'LastAvailableMonth': 12,
                                                                'BaseRun': 'PIcntrl',
                                                                'LastAvailableYear': 2000,
                                                                'BaseRealization': 'Run1'},
                                                      'Run 1': {'MonthsSimulated': 1692,
                                                                'FirstAvailableYear': 1860,
                                                                'YearInBaseRun': 2190,
                                                                'FirstAvailableMonth': 1,
                                                                'YearsSimulated': 141,
                                                                'LastAvailableMonth': 12,
                                                                'BaseRun': 'PIcntrl',
                                                                'LastAvailableYear': 2000,
                                                                'BaseRealization': 'Run1'},
                                                      'Run 3': {'MonthsSimulated': 1692,
                                                                'FirstAvailableYear': 1860,
                                                                'YearInBaseRun': 2240,
                                                                'FirstAvailableMonth': 1,
                                                                'YearsSimulated': 141,
                                                                'LastAvailableMonth': 12,
                                                                'BaseRun': 'PIcntrl',
                                                                'LastAvailableYear': 2000,
                                                                'BaseRealization': 'Run1'},
                                                      },
                                       'mri_cgcm2_3_2a': {'IPCCModelID': 'MRI-CGCM2.3.2',
                                                          'RunList': ['Run 1', 'Run 2','Run 3','Run 4','Run 5'],
                                                          'Run 1': {'MonthsSimulated': 1812,
                                                                    'FirstAvailableYear': 1850,
                                                                    'YearInBaseRun': 1851,
                                                                    'FirstAvailableMonth': 1,
                                                                    'YearsSimulated': 151,
                                                                    'LastAvailableMonth': 12,
                                                                    'BaseRun': 'PIcntrl  ',
                                                                    'LastAvailableYear': 2000,
                                                                    'BaseRealization': 'Run1'},
                                                          'Run 2': {'MonthsSimulated': 1812,
                                                                    'FirstAvailableYear': 1850,
                                                                    'YearInBaseRun': 1901,
                                                                    'FirstAvailableMonth': 1,
                                                                    'YearsSimulated': 151,
                                                                    'LastAvailableMonth': 12,
                                                                    'BaseRun': 'PIcntrl  ',
                                                                    'LastAvailableYear': 2000,
                                                                    'BaseRealization': 'Run1'},
                                                          'Run 3': {'MonthsSimulated': 1812,
                                                                    'FirstAvailableYear': 1850,
                                                                    'YearInBaseRun': 1951,
                                                                    'FirstAvailableMonth': 1,
                                                                    'YearsSimulated': 151,
                                                                    'LastAvailableMonth': 12,
                                                                    'BaseRun': 'PIcntrl  ',
                                                                    'LastAvailableYear': 2000,
                                                                    'BaseRealization': 'Run1'},
                                                          'Run 4': {'MonthsSimulated': 1812,
                                                                    'FirstAvailableYear': 1850,
                                                                    'YearInBaseRun': 2001,
                                                                    'FirstAvailableMonth': 1,
                                                                    'YearsSimulated': 151,
                                                                    'LastAvailableMonth': 12,
                                                                    'BaseRun': 'PIcntrl  ',
                                                                    'LastAvailableYear': 2000,
                                                                    'BaseRealization': 'Run1'},
                                                          'Run 5': {'MonthsSimulated': 1812,
                                                                    'FirstAvailableYear': 1850,
                                                                    'YearInBaseRun': 2051,
                                                                    'FirstAvailableMonth': 1,
                                                                    'YearsSimulated': 151,
                                                                    'LastAvailableMonth': 12,
                                                                    'BaseRun': 'PIcntrl  ',
                                                                    'LastAvailableYear': 2000,
                                                                    'BaseRealization': 'Run1'}
                                                          }
                                       }
